name        : libdaemon
version     : 0.14
release     : 3
source      :
    - http://0pointer.de/lennart/projects/libdaemon/libdaemon-0.14.tar.gz : fd23eb5f6f986dcc7e708307355ba3289abe03cc381fc47a80bca4a50aa6b834
homepage    : http://0pointer.de/lennart/projects/libdaemon/
license     :
    - GPL-2.0
component   : programming.library
summary     : The libdaemon package is a lightweight C library that eases the writing of UNIX daemons.
emul32      : yes
description : |
    The libdaemon package is a lightweight C library that eases the writing of UNIX daemons.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
